# Generated by Django 3.1.1 on 2020-09-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200905_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.URLField(default='https://github.com/mcfarlm3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='weburl',
            field=models.URLField(default='https://github.com/mcfarlm3'),
            preserve_default=False,
        ),
    ]
