# Generated by Django 3.1.1 on 2020-09-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200907_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='start_date',
        ),
        migrations.AddField(
            model_name='job',
            name='end_year',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_year',
            field=models.SmallIntegerField(null=True),
        ),
    ]
